language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

before_script:
  - npm prune

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov
